name: level-zero-tests
base: core24
confinement: strict
lint:
  ignore:
    - metadata
platforms:
  amd64:
    build-on: [amd64]
version: '1.16.1'
summary: Intel Level Zero Unit Tests

description: |
  Snap for building and running Intel's Level Zero unit tests
  from the Level Zero repository

apps:
  test:
    command: test
  list-tests:
    command: list_tests

parts:
  test-runner:
    source: bin/
    plugin: dump
    stage:
      - test

  list-tests-runner:
    source: bin/
    plugin: dump
    stage:
      - list_tests

  level-zero-sdk:
    plugin: nil
    source: https://github.com/oneapi-src/level-zero.git
    source-type: git
    source-branch: master
    build-attributes:
      - enable-patchelf
    build-packages:
      - build-essential
      - cmake
      - git
      - pkg-config
      - python3
    override-build: |
      set -eux

      cmake -S . -B build \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=/usr

      cmake --build build -j"$(nproc)"
      cmake --install build --prefix "${CRAFT_PART_INSTALL}/usr"

  level-zero-tests:
    plugin: nil
    source: https://github.com/oneapi-src/level-zero-tests.git
    source-type: git
    source-branch: master
    after:
      - level-zero-sdk
    build-attributes:
      - enable-patchelf
    build-packages:
      - build-essential
      - cmake
      - git
      - pkg-config
      - libboost-dev
      - libboost-log-dev
      - libboost-program-options-dev
      - libboost-timer-dev
      - libdrm-dev
      - libudev-dev
      - libssl-dev
      - libgtest-dev
      - libpng-dev
      - python3
    stage-packages:
      - cmake
      - libdrm2
      - libudev1
      - libssl3t64
      - libpng16-16t64
      - libboost-log1.83.0
      - libboost-program-options1.83.0
      - libboost-timer1.83.0
      - libstdc++6
    override-build: |
      set -eux

      export CMAKE_PREFIX_PATH="${CRAFT_STAGE}/usr:${CMAKE_PREFIX_PATH:-}"
      export LD_LIBRARY_PATH="${CRAFT_STAGE}/usr/lib:${CRAFT_STAGE}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}:${LD_LIBRARY_PATH:-}"

      cmake -S . -B build \
        -DCMAKE_BUILD_TYPE=Release

      cmake --build build -j"$(nproc)"

      # Stage the full build tree so ctest metadata and unit-test binaries
      # are available at runtime.
      mkdir -p "${CRAFT_PART_INSTALL}/usr/lib/level-zero-tests"
      cp -a build "${CRAFT_PART_INSTALL}/usr/lib/level-zero-tests/build"

      # Make unit-test binaries easy to discover from $PATH.
      mkdir -p "${CRAFT_PART_INSTALL}/usr/bin"
      find build -type f -name "*test*" -perm -111 -exec cp -a {} "${CRAFT_PART_INSTALL}/usr/bin/" \;
