name: level-zero-tests
base: core24
confinement: strict
lint:
  ignore:
    - metadata
platforms:
  amd64:
    build-on: [amd64]
version: '1.16.1'
summary: Intel Level Zero Unit Tests
license: MIT

description: |
  Snap for building and running Intel's Level Zero unit tests
  from the Level Zero repository

apps:
  test:
    command: test
    plugs:
      - opengl
      - hardware-observe
      - system-observe
  list-tests:
    command: list_tests
    plugs:
      - opengl
      - hardware-observe
      - system-observe

parts:
  test-runner:
    source: bin/
    plugin: dump
    stage:
      - test

  list-tests-runner:
    source: bin/
    plugin: dump
    stage:
      - list_tests

  level-zero-tests:
    plugin: nil
    source: https://github.com/oneapi-src/level-zero-tests.git
    source-type: git
    source-commit: 87cf732fcfb31a943082fb3ca7c17b729eaf4758
    build-attributes:
      - enable-patchelf
    build-packages:
      - build-essential
      - binutils
      - cmake
      - git
      - pkg-config
      - ninja-build
      - clang
      - ocl-icd-opencl-dev
      - libvulkan-dev
      - libgl1-mesa-dev
      - libglfw3-dev
      - libgles2-mesa-dev
      - glslang-tools
      - libboost-all-dev
      - libdrm-dev
      - libudev-dev
      - libze-dev
      - libssl-dev
      - libgtest-dev
      - libpng-dev
      - python3
    stage-packages:
      - cmake
      - libdrm2
      - libudev1
      - libpci3
      - pciutils
      - libigc1
      - libigdfcl1
      - libnl-3-200
      - libnl-route-3-200
      - libze-intel-gpu1
      - libze1
      - libssl3
      - libpng16-16
      - libboost-log1.83.0
      - libboost-program-options1.83.0
      - libboost-timer1.83.0
      - libboost-filesystem1.83.0
      - libboost-system1.83.0
      - libstdc++6
    override-build: |
      set -eux

      mkdir -p build
      cd build
      cmake \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX="${CRAFT_PART_INSTALL}/usr" \
        ..
      cmake --build . -j"$(nproc)" --config Release --target install
      cd ..

      mkdir -p "${CRAFT_PART_INSTALL}/level-zero-tests"
      cp -a . "${CRAFT_PART_INSTALL}/level-zero-tests/src"

      # Stage the full build tree so ctest metadata and unit-test binaries
      # are available at runtime.
      mkdir -p "${CRAFT_PART_INSTALL}/usr/lib/level-zero-tests"
      cp -a build "${CRAFT_PART_INSTALL}/usr/lib/level-zero-tests/build"

      # Make unit-test binaries easy to discover from $PATH.
      mkdir -p "${CRAFT_PART_INSTALL}/usr/bin"
      find build -type f -name "*test*" -perm -111 -exec cp -a {} "${CRAFT_PART_INSTALL}/usr/bin/" \;
      # test_device helpers are looked up under "<cwd>/device".
      mkdir -p "${CRAFT_PART_INSTALL}/usr/bin/device"
      find build/conformance_tests/core/test_device -type f -name "test_*helper*" -perm -111 \
        -exec cp -a {} "${CRAFT_PART_INSTALL}/usr/bin/device/" \;
      # Some tests load SPIR-V modules from the current working directory.
      find . -type f -name "*.spv" -exec cp -a {} "${CRAFT_PART_INSTALL}/usr/bin/" \;
